language: python
python:
- 3.5
install:
- pip install six pyyaml requests markdown2 jinja2
script:
- python validate_entries.py
deploy:
  provider: script
  script: site_generator/travis_deploy
  on:
    repo: dotastro/hacks-collector
    branch: master
env:
  global:
    secure: BDpLg8IuU9pV5Yny0/HPYuTEgaLkrdhhg12I223r6MKS9sON94tICNyTD+qFb8kGTx7wTSAV2s00248z70FY+PaRCLCr6geXPj/pEdNyfYR2xwSmpmDypJJywpmWlkWj96jZZrHueRtfnNdR2dzkOdF9yy/mN1H9U++7Iw7/rcWexh6sNrnHAZDZh1VrrIJiPR1X6Cj64/6/oHTF1PJ6rSl6L3kjinZyRhBMvqH+KDZ+WqcojImwBnl3/NCtnrYguKqinlrwVUeiLok1RCqQ8BN03GmJiz8f1GAP+YHAzVB0B4logc8Ag/SqjMHmWMhdd4eoDFrvaSrZxyj3d5Dtu/leFnwAzQBjtDTdqDxb519YwExLsoqLagHk8ZB68VAdiTgeNcNAEwALbIQH+fLRRatEvpAsIIVT0yMPTiDPmWAzz7lnzj/RGTqbHcMjILn2Vg7tE+Fq0lEaPCyoe/BUIWaHYPUggoOX9ydS/xoCL2IUw3fCCeWWV4dr+RFeoJGkMX6h/ej7zrJ/A/R92otP+qgbSlSjCd83/rlE5scKOvwaZ76FGxEo4BmfYdpsegdsm0aOZFPrRp8RmVZbqLv1hiDFPSN7NS8A5lG4/A4F0q3kyiuyMwncyGEKvgY30DoQdfDdt8LB4Kcz/mPUSHaUMQy0BAqpl0GpFbnkBHkGoOc=
