language: python

python:
  - 3.5

install:
  - pip install six pyyaml requests markdown2 jinja2

script:
  - python validate_entries.py

deploy:
    provider: script
    script: site_generator/travis_deploy
    on:
        repo: dotastro/hacks-collector
        branch: master

env:
    global:
        - secure: "l23IiIvcSudY8oLybxgR9RkWUYor1IYhOuVdKxUjfYrBjk55/7kNLETQudSMWGAXZ2mNhyhLdcAXQ57d6khAkjIAKFcxyMxSgvdr76xoUXeWa+T+ki6Y864QSylw1bdPtcxfA9RENZ4epdCi6QoJA7NTgr6awY08scfaC8Nosw0hf3p22+D/bUj6hRBwpmkwbBZjDXjW0GobAjJgwZHcpSKS81oWofLu+o2Nx2IJZENbbeBqSvLz2VZ+2cJVqCIQ2HcqSXvq4I30nRSxZpY/1cbbB9w2CPvalMvEsVfv/9Rp0fP4NcD/oiRaQ0v7fYskDOyYHE9bpb+Q0QJjlhQ+GgF9BY5UeDIKRW3mZW876J5ejqAu952YaAbAdgbA07HCh3izmipF3k4fB/1QMZUcHyt77yVqfHVtnqVWv0EWsSsdcgjsRkYp3wV70MrEvNKlSim4nZRLCjZKmAEyefPalCbzLWTQAXax0C43pp4Hea1HFl2uLawmEotkZSOtc1zPBPPVXf/sadiAgbZXummmoZyGOoyoXTTK7gCN3zZpCO57WWEIiSXG77UkSfyPo+lj/OY4OvnWpxsiSM5p2yUy89im95WgkAWhuLf0sYyTIX33YclbDp4CWlbwYKjTefRSwRpj8+8LbcidUopJJeAyaMEb3m2eYbLVlBQsOPvLASk="
