language: python

python:
  - 3.5

install:
  - pip install six pyyaml requests markdown2 jinja2

script:
  - python validate_entries.py

deploy:
    provider: script
    script: site_generator/travis_deploy
    on:
        repo: dotastro/hacks-collector
        branch: master

env:
    global:
        - secure: "RfKO9BvmVYkfAjx64j4Sy8a51zsG96X/eCD6o7RHb8U8HgtWhsUc3SshPozHr7mebgBUHRjXItU81uSkyhFkHMmFqNKU6RRcrNql98QhSrVe1/TS0f6BJ0TqmV5l9/NsFvF0HLEt8KRkjNylGBlK8jsHxLlTxxPnJZ8ou6y691ALQTh215RotgW7zsE3XUbx5NdC56aH/Gj1eVB/EGXArMtrMOKMISlKdNivt6RO8h8F//QQbNh9wk45Qm2B8zZ6dtUn7jeyAIuxQ7aH6ulUEmr8+YnC61Ify8Ogy4qyi0kiB6KcaxB6x2z833Zmd9STBUMTdO6t7JzYQmtcC38giaOMxcuhcseM+xMDlDl+kvtfB31uCybJ5IgewN0KOo01HgCWQfrod1d+sBiTyeJLGqqlyPx+3ahlGC5Y5DDj397GP0M9AJTf33CNOLZsYZGkxNTUZZbpSSZjZK6wcT99awBc36YSblqi9STyxer47hoAgh57CKTJrnVLt2lhEnhFZpghmjpnRhoLtwcSZxELEeWhb7ig66S3qOONp9m64eu6hM95yqL2k7KUn0B1PDuIcqbO/DDRrSJTCV/3UB77QvxaTlKozqsBHzOMwKAMBcwh42ZzrNBzuuTWStGXj6tBlAPuMjm5sTre/pE7/ggrRhuJLPhowWupeB7uqovM3nM="
